Website/Controllers/LoginAndRegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Website.Models;

namespace Website.Controllers
{
    public class LoginAndRegisterController : Controller
    {
        private Entities _db = new Entities();
        public ActionResult Index()
        {
            if (Session["id"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(admin admin)
        {
            if (ModelState.IsValid)
            {
                var check = _db.admins.FirstOrDefault(s => s.email == admin.email);
                if (check == null)
                {
                    if (admin.password == admin.ConfirmPassword)
                    {
                        admin.created_at = DateTime.Now;
                        admin.updated_at = DateTime.Now;
                        _db.Configuration.ValidateOnSaveEnabled = false;
                        _db.admins.Add(admin);
                        _db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.errorConfirm = "Mat khau xac thuc khong dung";
                        return View();
                    }
                }
                else
                {
                    ViewBag.errorEmail = "Email da ton tai";
                    return View();
                }
            }
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string email, string password)
        {
            if (ModelState.IsValid)
            {
                var f_password = password;
                var data = _db.admins.Where(s => s.email.Equals(email) && s.password.Equals(f_password)).ToList();
                if (data.Count() > 0)
                {
                    //add session
                    Session["FullName"] = data.FirstOrDefault().name;
                    Session["Email"] = data.FirstOrDefault().email;
                    Session["id"] = data.FirstOrDefault().id;
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.error = "Login failed";
                    return RedirectToAction("Login");
                }
            }
            return View();
        }


        //Logout
        public ActionResult Logout()
        {
            Session.Clear();//remove session
            return RedirectToAction("Login");
        }
    }
}

Website/Views/LoginAndRegister/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Trangchu/Index.cshtml";

}
<div class="row justify-content-md-start">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Wellcome
            </div>
            <div class="card-body">
                @if (Session["FullName"] != null)
                {
                    <p>Name: @Session["FullName"].ToString()</p>
                    <p>Email: @Session["Email"].ToString()</p>
                    <a href="@Url.Action("Logout","LoginAndRegister")" class="btn btn-warning">Logout</a>
                }
            </div>
        </div>

    </div>
</div>

Website/Views/LoginAndRegister/Login.cshtml
@model Website.Models.admin

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<div class="row justify-content-md-center">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Login
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Login", "LoginAndRegister", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        @Html.LabelFor(m => m.email)
                        @Html.TextBoxFor(m => m.email, "", new { @class = "form-control", @placeholder = "Email" })

                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.password)
                        @Html.PasswordFor(m => m.password, new { @class = "form-control", @placeholder = "Password" })
                    </div>
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-primary" value="Login" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Website/Views/LoginAndRegister/Register.cshtml
@model Website.Models.admin

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="row justify-content-md-center">
    <div class="col-md-5">
        @using (Html.BeginForm("Register", "LoginAndRegister", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Register</div>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        @Html.LabelFor(m => m.name)
                        @Html.TextBoxFor(m => m.name, "", new { @class = "form-control", @placeholder = "Name" })
                        @Html.ValidationMessageFor(m => m.name, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.email)
                        @Html.TextBoxFor(m => m.email, "", new { @class = "form-control", @placeholder = "Email" })
                        @Html.ValidationMessageFor(m => m.email, "", new { @class = "badge badge-danger" })
                        @if (ViewBag.errorEmail != null)
                        {
                            <span class="badge badge-danger", style="color:red">@ViewBag.errorEmail</span>
                        }
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.phone)
                        @Html.TextBoxFor(m => m.phone, "", new { @class = "form-control", @placeholder = "Phone" })
                        @Html.ValidationMessageFor(m => m.phone, "", new { @class = "badge badge-danger" })

                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.avatar)
                        @Html.TextBoxFor(m => m.avatar, new { @class = "form-control", @placeholder = "Avatar" })
                        @Html.ValidationMessageFor(m => m.avatar, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.active)
                        @Html.TextBoxFor(m => m.active, new { @class = "form-control", @placeholder = "Active" })
                        @Html.ValidationMessageFor(m => m.active, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.password)
                        @Html.PasswordFor(m => m.password, new { @class = "form-control", @placeholder = "Password" })
                        @Html.ValidationMessageFor(m => m.password, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.remember_token)
                        @Html.TextBoxFor(m => m.remember_token, new { @class = "form-control", @placeholder = "Remember Token" })
                        @Html.ValidationMessageFor(m => m.remember_token, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.ConfirmPassword)
                        @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control", @placeholder = "Confim Password" })
                        @Html.ValidationMessageFor(m => m.ConfirmPassword, "", new { @class = "badge badge-danger" })
                        @if (ViewBag.errorConfirm != null)
                        {
                            <span class="badge badge-danger" , style="color:red">@ViewBag.errorConfirm</span>
                        }
                    </div>
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-danger" value="Register" />
                    </div>
                </div>
            </div>

        }
    </div>
</div>